
    var toutiao =  [{
      "liveInfo": null,
      "tcount": 0,
      "picInfo": [],
      "docid": "DV5I0I1U000189FH",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV5I0I1U000189FH.html",
      "source": "央视新闻移动网",
      "title": "牢记嘱托 把改革开放不断推向深入",
      "type": "doc",
      "imgsrcFrom": "doc",
      "imgsrc3gtype": 0,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "央视网消息（新闻联播）：习近平总书记近日在广东考察时强调，要",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 22:07:40"
    }, {
      "liveInfo": null,
      "tcount": 0,
      "picInfo": [],
      "docid": "DV4TQ4RR000189FH",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV4TQ4RR000189FH.html",
      "source": "新华网$",
      "title": "学习贯彻习近平广东考察重要讲话精神",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 0,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "十月的南粤大地，洋溢收获的喜悦，升腾无限的希望。时隔６年，习",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 16:14:38"
    }, {
      "liveInfo": null,
      "tcount": 435,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/85687b7696e749f8b53cd0497faa28b0.png",
        "height": null
      }],
      "docid": "DV52NKQ10001875P",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV52NKQ10001875P.html",
      "source": "政事儿",
      "title": "公安部原副部长孟宏伟，一重要资格被撤",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "10月26日，政协第十三届全国委员会第十一次主席会议暨主席会",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 17:40:39"
    }, {
      "liveInfo": null,
      "tcount": 13346,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/575006b1167d40fb9e986901a4dcb28e.png",
        "height": null
      }],
      "docid": "DV4SG59F0001875O",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV4SG59F0001875O.html",
      "source": "封面新闻-华西都市报",
      "title": "年轻夫妇花14元淘旧棋盘 发现其内竟暗藏6枚钻戒",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "《每日邮报》27日报道，近日，一对年轻夫妇在花了2美元（编者",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 15:51:42"
    }, {
      "liveInfo": null,
      "tcount": 0,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/8e9a1e056ced46118bda9e4816f9ff8d.png",
        "height": null
      }],
      "docid": "DV5FOGNJ000187VE",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV5FOGNJ000187VE.html",
      "source": "澎湃新闻",
      "title": "美防长:下周将在美与中国国防部长魏凤和会面",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "继中美两国国防部长在新加坡东盟防长扩大会上会晤后，美国国防部",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 21:22:00"
    }, {
      "liveInfo": null,
      "tcount": 25174,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/a5e7cea53c0d4e2aaa846bb8a12c9922.png",
        "height": null
      }],
      "docid": "DV514AI20001875O",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV514AI20001875O.html",
      "source": "海外网",
      "title": "\"大篷车\"移民拒挽留执意赴美 美民众带枪抵达边境",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "海外网10月27日电当地时间26日，墨西哥总统涅托为了挽留“",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 17:12:37"
    }, {
      "liveInfo": null,
      "tcount": 262,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/d5dfa45ad9484498ae745e3d87b1653b.png",
        "height": null
      }],
      "docid": "DV5F5J210001875N",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV5F5J210001875N.html",
      "source": "法制晚报·看法新闻",
      "title": "老板放高利贷打死人刑拘37天 \"保护伞\"局长获刑8年",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "法制晚报·看法新闻佛山司法局原党委书记、局长、佛山监狱第一政",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 21:17:59"
    }, {
      "liveInfo": null,
      "tcount": 2734,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/5340554c07b24250b48bb57694d2437a.png",
        "height": null
      }],
      "docid": "DV58DPDF0001899O",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV58DPDF0001899O.html",
      "source": "浙江新闻",
      "title": "中国首枚民营运载火箭朱雀一号搭载卫星未能入轨 ",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "浙江新闻客户端10月27日消息，记者从酒泉卫星发射中心最新获",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 19:20:08"
    }, {
      "liveInfo": null,
      "tcount": 397,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/e258b52d04b048e9b851e07017e1a952.png",
        "height": null
      }],
      "docid": "DV5669KV0001875P",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV5669KV0001875P.html",
      "source": "大河网-大河报",
      "title": "女子回娘家遭挟持 劫匪称有人花钱要其全家人性命",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "前不久，开封通许的娄女士回了趟娘家。没有想到，这竟成了一次惊",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 18:41:05"
    }, {
      "liveInfo": null,
      "tcount": 84,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/894b9d041a1846e289f4c4c65f820c9e.png",
        "height": null
      }],
      "docid": "DV5DGMHS051188EA",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV5DGMHS051188EA.html",
      "source": "虎嗅APP",
      "title": "首枚民营运载火箭卫星未能入轨 你应该知道的更多",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "今天下午16点0分0秒，中国大地深处的酒泉发射中心，一枚红白",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "推荐",
      "ptime": "2018-10-27 20:49:36"
    }, {
      "liveInfo": null,
      "tcount": 1940,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/04735f5aca394299917fdb1b4343f3c0.png",
        "height": null
      }],
      "docid": "DV5CPE030001875P",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV5CPE030001875P.html",
      "source": "齐鲁晚报",
      "title": "网友买灰黑色床单被套 亲妈发飙:想让我早点升天?",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "近日，网友晒出的一则聊天记录引发热议“自己买了一套灰黑色床单",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 20:36:23"
    }, {
      "liveInfo": null,
      "tcount": 34,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/ec73c641edcd40a19a8b0ede6173e0f7.jpeg",
        "height": null
      }],
      "docid": "DV5C0FVR0530L4D3",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV5C0FVR0530L4D3.html",
      "source": "大白新闻",
      "title": "革命世家出身前市委书记获刑 党报曾刊其反腐讲话",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "【编辑/王瑞文统筹/刘姝蓉】2018年10月26日，三门峡市",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "推荐",
      "ptime": "2018-10-27 20:22:49"
    }, {
      "liveInfo": null,
      "tcount": 12790,
      "picInfo": [{
        "ref": null,
        "width": null,
        "url": "http://cms-bucket.nosdn.127.net/2018/10/27/5cf89651bdfd4783b163dd09bbc28b49.png",
        "height": null
      }],
      "docid": "DV4O6AIV0001875P",
      "videoInfo": null,
      "channel": "",
      "link": "https://3g.163.com/all/article/DV4O6AIV0001875P.html",
      "source": "每日经济新闻",
      "title": "清华总裁班34位同学开餐厅却破产 背后故事竟这样",
      "type": "doc",
      "imgsrcFrom": null,
      "imgsrc3gtype": 1,
      "unlikeReason": "重复、旧闻/6,内容质量差/6",
      "digest": "据北京海淀法院网，近日，清华大学总裁班34名学员，通过众筹开",
      "typeid": "",
      "addata": null,
      "tag": "",
      "category": "新闻",
      "ptime": "2018-10-27 14:36:26"
    }]
